before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: better-whisper
    ldflags:
      - -s -w

checksum:
  name_template: "checksums.txt"


release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: better-whisper
    homepage: "https://github.com/akash-joshi/better-whisper"
    description: "A better CLI for whisper-cpp"
    tap:
      owner: akash-joshi
      name: homebrew-better-whisper
    install: |
      bin.install "better-whisper"
    test: |
      system "#{bin}/better-whisper", "--version"
    dependencies:
      - name: "whisper-cpp"
      - name: "ffmpeg"
