version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: better-whisper
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: better-whisper
    homepage: "https://github.com/akash-joshi/better-whisper"
    description: "A better CLI for whisper-cpp"
    repository:
      owner: akash-joshi
      name: homebrew-akash-joshi
      branch: main
      pull_request:
        enabled: false

    commit_author:
      name: akash-joshi
      email: git@thewriting.dev

    dependencies:
      - name: "whisper-cpp"
      - name: "ffmpeg"
